import { Platform } from 'react-native';

export const strings = {
  app: {
    name: 'BirthReady Dads',
    tagline: 'Be ready for birth day',
  },
  auth: {
    signIn: 'Sign In',
    signUp: 'Create Account',
    email: 'Email',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    forgotPassword: 'Forgot Password?',
    signInWithApple: 'Continue with Apple',
    signInWithGoogle: 'Continue with Google',
    signInWithEmail: 'Continue with Email',
    orContinueWithMagicLink: 'Or sign in with a link',
    noAccount: "Don't have an account?",
    hasAccount: 'Already have an account?',
    signUpLink: 'Sign Up',
    signInLink: 'Sign In',
    magicLinkSent: 'Check your email for a sign-in link',
    sendMagicLink: 'Send Link',
    resetPassword: 'Reset Password',
    resetPasswordSent: 'Password reset email sent',
  },
  onboarding: {
    welcome: {
      title: 'Welcome to BirthReady Dads',
      subtitle: "You're going to be a dad. Let's make sure you're ready.",
    },
    dueDate: {
      title: "When is your due date?",
      subtitle: "We'll personalize your content based on your timeline",
      placeholder: 'Select due date',
      skip: "I don't know yet",
    },
    pregnancyNumber: {
      title: "Is this your first baby?",
      subtitle: "We'll tailor the content to your experience level",
      first: 'First baby',
      second: 'Second baby',
      thirdPlus: 'Third or more',
    },
    notifications: {
      title: 'Stay on track',
      subtitle: 'Get weekly reminders and updates about your journey',
      enable: 'Enable Notifications',
      later: 'Maybe Later',
      weeklyReminder: 'Weekly module reminder',
      laborApproaching: 'Labor is approaching',
      mentalHealth: 'Mental health check-in',
    },
  },
  home: {
    thisWeek: "This Week",
    yourProgress: 'Your Progress',
    modulesCompleted: 'modules completed',
    mentalHealthCheckIn: 'How are you holding up?',
    mentalHealthSubtitle: 'Take a quick check-in',
    takeCheckIn: 'Take Check-In',
    contractionTimer: 'Contraction Timer',
    contractionTimerSubtitle: "It's time to start tracking",
    openTimer: 'Open Timer',
  },
  module: {
    play: 'Play',
    pause: 'Pause',
    download: 'Download',
    downloaded: 'Downloaded',
    bookmark: 'Bookmark',
    bookmarked: 'Bookmarked',
    whatsNext: "What's Next",
    continueListening: 'Continue Listening',
    startListening: 'Start Listening',
    completed: 'Completed',
  },
  contractionTimer: {
    title: 'Contraction Timer',
    start: 'Start',
    stop: 'Stop',
    currentDuration: 'Current Duration',
    interval: 'Interval',
    contractions: 'Contractions',
    fiveOneOneAlert: 'Many providers suggest calling around this point — check your birth plan',
    reset: 'Reset Timer',
    export: 'Export Log',
    noContractions: 'No contractions recorded yet',
    tapToStart: 'Tap to start timing a contraction',
  },
  mentalHealth: {
    title: 'Mental Health Check-In',
    subtitle: 'A quick check-in to see how you are doing',
    questionPrefix: 'Question',
    of: 'of',
    submit: 'Submit Check-In',
    lowRisk: {
      title: "You're doing great",
      subtitle: 'Keep taking care of yourself and your growing family',
    },
    elevatedRisk: {
      title: 'We want you to know',
      subtitle: "It's normal to feel overwhelmed. Here are some resources that might help.",
      resources: 'View Resources',
    },
    accessAnytime: 'You can access this check-in anytime from your profile',
  },
  paywall: {
    title: 'Unlock Full Journey',
    subtitle: 'Get access to all modules, advocacy tools, and the complete postpartum track',
    freeTier: 'Free',
    freeTierFeatures: [
      'Weekly pregnancy audio modules',
      'Contraction timer',
      'Hospital checklist',
      'Core labor stage modules',
      'Mental health check-ins',
    ],
    premium: 'Premium',
    premiumPriceMonthly: '$9.99/mo',
    premiumPriceYearly: '$79/year',
    premiumPriceLifetime: '$129 lifetime',
    premiumFeatures: [
      'All 7 labor stage modules',
      'Emergency scenario training',
      'Birth advocacy scripts',
      'Complete postpartum track',
      'Partner Premium access',
    ],
    startFreeTrial: 'Start 7-Day Free Trial',
    maybeLater: 'Maybe Later',
    giftThis: 'Gift this',
    restorePurchases: 'Restore Purchases',
    cancelAnytime: 'Cancel anytime',
    noChargeUntil: "You won't be charged until",
  },
  profile: {
    title: 'Profile',
    dueDate: 'Due Date',
    pregnancyNumber: 'Pregnancy Number',
    editDueDate: 'Edit Due Date',
    notifications: 'Notifications',
    subscription: 'Subscription',
    upgradeToPremium: 'Upgrade to Premium',
    manageSubscription: 'Manage Subscription',
    mentalHealth: 'Mental Health',
    viewCheckIns: 'View Check-Ins',
    partner: 'Partner',
    linked: 'Linked',
    notLinked: 'Not Linked',
    shareCode: 'Share Your Code',
    enterPartnerCode: "Enter Partner's Code",
    deleteAccount: 'Delete Account',
    deleteAccountConfirm: 'Are you sure? This action cannot be undone.',
  },
  common: {
    loading: 'Loading...',
    error: 'Something went wrong',
    retry: 'Try Again',
    cancel: 'Cancel',
    save: 'Save',
    done: 'Done',
    next: 'Next',
    back: 'Back',
    skip: 'Skip',
    close: 'Close',
    signOut: 'Sign Out',
  },
  errors: {
    generic: 'Something went wrong. Please try again.',
    network: 'Please check your connection and try again.',
    auth: {
      invalidCredentials: 'Invalid email or password',
      emailInUse: 'This email is already in use',
      weakPassword: 'Password must be at least 8 characters',
      userNotFound: 'No account found with this email',
      emailNotVerified: 'Please verify your email address',
      sessionExpired: 'Your session has expired. Please sign in again.',
    },
  },
};

export type StringKey = keyof typeof strings;
